import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';
import { basename, extname } from 'node:path';
import { estimateTokens } from '../utils/tokens.js';

function shouldIncludeModule(
  mod: ContextModule,
  sections: { include: string[]; exclude: string[] },
): boolean {
  const stem = basename(mod.filename, extname(mod.filename));
  if (sections.exclude.length > 0 && sections.exclude.includes(stem)) {
    return false;
  }
  if (sections.include.length > 0 && !sections.include.includes(stem)) {
    return false;
  }
  return true;
}

function stripHeading(content: string): string {
  return content.replace(/^#\s+.+\n?/, '').trim();
}

function isModuleFile(mod: ContextModule, config: AgentCtxConfig): boolean {
  // Check if this module's config path contains 'modules/'
  return config.context.some(
    p => basename(p) === mod.filename && p.includes('modules/')
  );
}

function extractFirstParagraph(content: string): string {
  const stripped = stripHeading(content);
  const lines = stripped.split('\n');
  const para: string[] = [];
  for (const line of lines) {
    if (para.length > 0 && line.trim() === '') break;
    if (line.startsWith('#')) break;
    if (line.trim()) para.push(line.trim());
  }
  return para.join(' ').slice(0, 200);
}

function extractExports(content: string): string[] {
  const exports: string[] = [];
  const lines = content.split('\n');
  let inExports = false;
  for (const line of lines) {
    if (/^##\s+exports/i.test(line)) { inExports = true; continue; }
    if (/^##\s+/i.test(line) && inExports) break;
    if (inExports && line.startsWith('- ')) {
      const match = line.match(/^-\s+`([^`]+)`/);
      if (match) exports.push(match[1]);
      else exports.push(line.replace(/^-\s+/, '').slice(0, 60));
    }
  }
  return exports.slice(0, 5);
}

function extractKeyFiles(content: string): string[] {
  const files: string[] = [];
  const lines = content.split('\n');
  let inFiles = false;
  for (const line of lines) {
    if (/^##\s+key files/i.test(line)) { inFiles = true; continue; }
    if (/^##\s+/i.test(line) && inFiles) break;
    if (inFiles && line.startsWith('- ')) {
      const match = line.match(/^-\s+`([^`]+)`/);
      if (match) files.push(match[1]);
    }
  }
  return files.slice(0, 5);
}

export function generateClaude(
  modules: ContextModule[],
  config: AgentCtxConfig,
): string {
  const sections = config.outputs.claude?.sections ?? {
    include: [],
    exclude: [],
  };

  const filtered = modules.filter((m) => shouldIncludeModule(m, sections));

  // Separate modules by tier
  const conventionModules = filtered.filter(m => !isModuleFile(m, config));
  const featureModules = filtered.filter(m => isModuleFile(m, config));

  const parts: string[] = [
    '<!-- Generated by agentctx — do not edit directly -->',
    '<!-- Source: .agentctx/ | Regenerate: npx agentctx generate -->',
    '',
    `# ${config.project.name}`,
  ];

  // ── L0: Project summary (always read) ───────────────────────────────

  if (config.project.language || config.project.framework || (config.skills && config.skills.length > 0)) {
    parts.push('');
    const meta: string[] = [];
    if (config.project.language) meta.push(`**Language:** ${config.project.language}`);
    if (config.project.framework) meta.push(`**Framework:** ${config.project.framework}`);
    if (config.skills && config.skills.length > 0) {
      meta.push(`**Skills:** ${config.skills.filter(s => s !== 'workflow').join(', ')}`);
    }
    parts.push(meta.join(' | '));
  }

  // Module index (L1 summary) — only if there are feature modules
  if (featureModules.length > 0) {
    parts.push('');
    parts.push('## Module Index');
    parts.push('');
    parts.push('> Read the full module file in `.agentctx/context/modules/` when working in that area.');
    parts.push('');

    for (const mod of featureModules) {
      const keyFiles = extractKeyFiles(mod.content);
      const exports = extractExports(mod.content);
      const summary = extractFirstParagraph(mod.content);

      // Find the config path for this module
      const configPath = config.context.find(p => basename(p) === mod.filename && p.includes('modules/'));
      const displayPath = configPath ? `.agentctx/${configPath}` : `.agentctx/context/modules/${mod.filename}`;

      let line = `- **${mod.title}** (\`${displayPath}\`)`;
      if (keyFiles.length > 0) {
        line += ` — ${keyFiles.slice(0, 3).map(f => `\`${f}\``).join(', ')}`;
      }
      parts.push(line);

      if (exports.length > 0) {
        parts.push(`  Exports: ${exports.map(e => `\`${e}\``).join(', ')}`);
      } else if (summary) {
        parts.push(`  ${summary}`);
      }
    }

    parts.push('');
    parts.push('---');
  }

  // ── L0: Conventions (always included inline) ────────────────────────

  for (let i = 0; i < conventionModules.length; i++) {
    const mod = conventionModules[i];
    parts.push('');
    parts.push(`## ${mod.title}`);
    parts.push('');
    parts.push(stripHeading(mod.content));
    if (i < conventionModules.length - 1) {
      parts.push('');
      parts.push('---');
    }
  }

  // ── Context Maintenance Protocol ────────────────────────────────────

  parts.push('');
  parts.push('---');
  parts.push('');
  parts.push('## Context Maintenance Protocol');
  parts.push('');
  parts.push('This project uses agentctx for living documentation. After implementing features or making significant changes, maintain the context files:');
  parts.push('');
  parts.push('### After implementing a feature');
  parts.push('1. Create or update a module file in `.agentctx/context/modules/<feature-name>.md`');
  parts.push('2. Document: key files created/modified, exported functions/components, dependencies on other modules');
  parts.push('3. Follow this format:');
  parts.push('');
  parts.push('```markdown');
  parts.push('# <Module Name>');
  parts.push('');
  parts.push('## Key Files');
  parts.push('- `src/path/to/file.ts` — brief description of purpose');
  parts.push('');
  parts.push('## Exports');
  parts.push('- `functionName()` — what it does');
  parts.push('- `ComponentName` — what it renders');
  parts.push('');
  parts.push('## Dependencies');
  parts.push('- Uses: list modules this depends on');
  parts.push('- Used by: list modules that depend on this');
  parts.push('');
  parts.push('## Notes');
  parts.push('- Implementation details, gotchas, planned changes');
  parts.push('```');
  parts.push('');
  parts.push('### After making an architectural decision');
  parts.push('Append to `.agentctx/context/decisions.md`:');
  parts.push('- What was decided and why');
  parts.push('- Alternatives that were considered');
  parts.push('- Date of the decision');
  parts.push('');
  parts.push('### After completing work');
  parts.push('Update `.agentctx/context/status.md`:');
  parts.push('- Move completed items from "In Progress" to "Recently Completed"');
  parts.push('- Add any new known issues discovered');
  parts.push('');
  parts.push('### When asked to implement a new feature');
  parts.push('1. Suggest creating a spec first: "Let me create a spec for this. Run `/spec` to define the requirements."');
  parts.push('2. Do not start coding without an approved spec in `specs/`');
  parts.push('3. If the user wants to proceed without a spec, at minimum document what will be built in a module file first');
  parts.push('');
  parts.push('### Auto-checkpoint');
  parts.push('After completing any significant implementation:');
  parts.push('1. Stage changes and create a checkpoint: `git add -A && git commit -m "checkpoint: {description}" && git tag cp-{name}`');
  parts.push('2. This creates a restore point the user can rollback to');
  parts.push('');
  parts.push('### Before creating new code');
  parts.push('1. Check the **Module Index** above — reuse exported functions instead of creating duplicates');
  parts.push('2. Read the full module file (`.agentctx/context/modules/<name>.md`) when working in that area');
  parts.push('3. Check `.agentctx/context/architecture.md` for directory conventions — put new files in the right place');
  parts.push('4. Check `.agentctx/context/decisions.md` for prior decisions that may affect your approach');

  return parts.join('\n') + '\n';
}
