import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';
import { basename, extname } from 'node:path';

function shouldIncludeModule(
  mod: ContextModule,
  sections: { include: string[]; exclude: string[] },
): boolean {
  const stem = basename(mod.filename, extname(mod.filename));
  if (sections.exclude.length > 0 && sections.exclude.includes(stem)) {
    return false;
  }
  if (sections.include.length > 0 && !sections.include.includes(stem)) {
    return false;
  }
  return true;
}

function isModuleFile(mod: ContextModule, config: AgentCtxConfig): boolean {
  return config.context.some(
    p => basename(p) === mod.filename && p.includes('modules/')
  );
}

function isConventionFile(mod: ContextModule, config: AgentCtxConfig): boolean {
  return config.context.some(
    p => basename(p) === mod.filename && p.includes('conventions/')
  );
}

function isAgentFile(mod: ContextModule, config: AgentCtxConfig): boolean {
  return config.context.some(
    p => basename(p) === mod.filename && p.includes('agents/')
  );
}

function isReferenceFile(mod: ContextModule, config: AgentCtxConfig): boolean {
  return config.context.some(
    p => basename(p) === mod.filename && p.includes('references/')
  );
}

function extractExports(content: string): string[] {
  const exports: string[] = [];
  const lines = content.split('\n');
  let inExports = false;
  for (const line of lines) {
    if (/^##\s+exports/i.test(line)) { inExports = true; continue; }
    if (/^##\s+/i.test(line) && inExports) break;
    if (inExports && line.startsWith('- ')) {
      const match = line.match(/^-\s+`([^`]+)`/);
      if (match) exports.push(match[1]);
      else exports.push(line.replace(/^-\s+/, '').slice(0, 60));
    }
  }
  return exports.slice(0, 5);
}

function extractKeyFiles(content: string): string[] {
  const files: string[] = [];
  const lines = content.split('\n');
  let inFiles = false;
  for (const line of lines) {
    if (/^##\s+key files/i.test(line)) { inFiles = true; continue; }
    if (/^##\s+/i.test(line) && inFiles) break;
    if (inFiles && line.startsWith('- ')) {
      const match = line.match(/^-\s+`([^`]+)`/);
      if (match) files.push(match[1]);
    }
  }
  return files.slice(0, 5);
}

export function generateClaude(
  modules: ContextModule[],
  config: AgentCtxConfig,
): string {
  const sections = config.outputs.claude?.sections ?? {
    include: [],
    exclude: [],
  };

  const filtered = modules.filter((m) => shouldIncludeModule(m, sections));

  // Categorize modules
  const featureModules = filtered.filter(m => isModuleFile(m, config));
  const hasConventions = filtered.some(m => isConventionFile(m, config));
  const hasAgents = filtered.some(m => isAgentFile(m, config));
  const hasReferences = filtered.some(m => isReferenceFile(m, config));
  const hasModules = featureModules.length > 0;

  // Check for standalone context files (architecture, decisions, status, workflow)
  const hasArchitecture = config.context.some(p => basename(p) === 'architecture.md');
  const hasDecisions = config.context.some(p => basename(p) === 'decisions.md');
  const hasStatus = config.context.some(p => basename(p) === 'status.md');
  const hasWorkflow = config.context.some(p => basename(p) === 'workflow.md');

  const parts: string[] = [
    '<!-- Generated by agentctx — do not edit directly -->',
    '',
    `# ${config.project.name}`,
  ];

  // ── Metadata line ────────────────────────────────────────────────────

  const meta: string[] = [];
  if (config.project.language) meta.push(config.project.language);
  if (config.project.framework) meta.push(config.project.framework);
  if (config.skills && config.skills.length > 0) {
    meta.push(`Skills: ${config.skills.filter(s => s !== 'workflow').join(', ')}`);
  }
  if (config.agent) {
    meta.push(`Agent: ${config.agent}`);
  }
  if (meta.length > 0) {
    parts.push('');
    parts.push(meta.join(' | '));
  }

  // ── Context Routing ─────────────────────────────────────────────────

  parts.push('');
  parts.push('## Context Routing');
  parts.push('');
  parts.push('All context lives in `.agentctx/context/`. Read ONLY what\'s relevant to your current task:');
  parts.push('');

  // Task-based routing — detect which skill convention dirs exist from config.context paths
  parts.push('### By task type');
  parts.push('| Working on | Read first | Also read |');
  parts.push('|---|---|---|');

  const lang = config.project.language || '';
  const framework = config.project.framework || '';

  // Detect which namespaced skill directories exist in the context paths
  const conventionDirs = new Set<string>();
  const referenceDirs = new Set<string>();
  for (const p of config.context) {
    const convMatch = p.match(/context\/conventions\/([^/]+)\//);
    if (convMatch) conventionDirs.add(convMatch[1]);
    const refMatch = p.match(/context\/references\/([^/]+)\//);
    if (refMatch) referenceDirs.add(refMatch[1]);
  }

  if (framework === 'nextjs' || conventionDirs.has('nextjs')) {
    parts.push('| React pages/routes | `conventions/nextjs/` (Quick Rules) | `references/nextjs/` |');
    parts.push('| Data fetching, APIs | `conventions/nextjs/` (Quick Rules) | `conventions/typescript/` |');
  }
  if (conventionDirs.has('design') || conventionDirs.has('tailwind')) {
    const readFirst = conventionDirs.has('design') ? '`conventions/design/`' : '`conventions/tailwind/`';
    const alsoRead = referenceDirs.has('design') ? '`references/design/`' : '';
    const tailwindPart = conventionDirs.has('tailwind') && conventionDirs.has('design') ? ' or `conventions/tailwind/`' : '';
    parts.push(`| Styling/CSS | ${readFirst}${tailwindPart} | ${alsoRead} |`);
  }
  if (lang === 'typescript' || lang === 'javascript' || conventionDirs.has('typescript')) {
    parts.push('| TypeScript logic | `conventions/typescript/` (Quick Rules) | relevant `modules/*.md` |');
  }
  if (lang === 'python') {
    parts.push('| Python code | `conventions/python-fastapi/` | relevant `modules/*.md` |');
  }
  parts.push('| New feature area | `modules/*.md` (check what exists) | `architecture.md`, `decisions.md` |');
  parts.push('| Starting a session | `status.md` (what happened last) | Module Index below |');
  parts.push('');

  // File-level routing
  parts.push('### By directory');
  parts.push('| File location | Context |');
  parts.push('|---|---|');
  if (hasConventions) {
    parts.push('| `conventions/{skill}/*.md` | Read Quick Rules section always, full Patterns section when implementing |');
  }
  if (hasModules) {
    parts.push('| `modules/*.md` | Read the specific module for the area you\'re working in |');
  }
  if (hasAgents) {
    parts.push('| `agents/*.md` | Read matching specialist for the task |');
  }
  if (hasReferences) {
    parts.push('| `references/{skill}/*.md` | Look up syntax or patterns when needed |');
  }
  parts.push('');

  // Convention files structure hint
  if (hasConventions) {
    parts.push('> Convention files have 3 layers: **Quick Rules** (always read, ~10 lines) → **Patterns** (read when implementing) → **Don\'t** (read before submitting)');
    parts.push('');
  }

  // ── Module Index ─────────────────────────────────────────────────────

  if (featureModules.length > 0) {
    parts.push('');
    parts.push('## Module Index');
    parts.push('');
    parts.push('> Check here first before creating new code. Read the full module file when working in that area.');
    parts.push('');

    for (const mod of featureModules) {
      const keyFiles = extractKeyFiles(mod.content);
      const exports = extractExports(mod.content);

      const configPath = config.context.find(p => basename(p) === mod.filename && p.includes('modules/'));
      const displayPath = configPath ? `.agentctx/${configPath}` : `.agentctx/context/modules/${mod.filename}`;

      let line = `- **${mod.title}** (\`${displayPath}\`)`;
      if (keyFiles.length > 0) {
        line += ` — ${keyFiles.slice(0, 3).map(f => `\`${f}\``).join(', ')}`;
      }
      if (exports.length > 0) {
        line += ` | Exports: ${exports.map(e => `\`${e}\``).join(', ')}`;
      }
      parts.push(line);
    }
  }

  // ── Protocol ─────────────────────────────────────────────────────────

  parts.push('');
  parts.push('## Protocol');
  parts.push('');
  parts.push('### At conversation start');
  parts.push('1. Read `status.md` — understand what happened in the last session');
  parts.push('2. Read Module Index below — know what code exists');
  parts.push('3. Read matching agent file from `agents/` if one is installed');
  parts.push('');
  parts.push('### Before writing code');
  parts.push('1. Check Module Index — reuse existing exports, don\'t duplicate');
  parts.push('2. Read the relevant convention file `Quick Rules` section (see Context Routing above)');
  parts.push('3. Read `architecture.md` for where to put new files');
  parts.push('4. Read the full `Patterns` section of relevant conventions only when implementing in that area');
  parts.push('');
  parts.push('### After implementing');
  parts.push('1. Create/update module file in `modules/{feature}.md` with: Key Files, Exports, Dependencies');
  parts.push('2. Log decisions in `decisions.md` (what, why, alternatives, consequences)');
  parts.push('3. Update `status.md` with what was done, what\'s unfinished, and any issues found');
  parts.push('');
  parts.push('### At end of session');
  parts.push('Update `status.md` with:');
  parts.push('- What was accomplished in this session');
  parts.push('- What\'s unfinished or blocked');
  parts.push('- Any user preferences observed (coding style, PR size, etc.)');
  parts.push('- Known issues discovered');
  parts.push('');
  parts.push('### When asked to build a new feature');
  const hasWorkflowSkill = config.skills?.includes('workflow');
  if (hasWorkflowSkill) {
    parts.push('**MANDATORY**: Do NOT start implementing without an approved spec.');
    parts.push('1. Run `/spec` to create a feature specification first');
    parts.push('2. The spec must be approved via `/approve` before any code is written');
    parts.push('3. If the user insists on skipping, explain: "Specs prevent wasted work and ensure we build the right thing. It takes 2 minutes."');
    parts.push('4. For small fixes/tweaks (< 10 lines), a spec is not required — just implement directly');
  } else {
    parts.push('Suggest `/spec` first — plan before coding');
  }
  parts.push('');
  parts.push('### Agent discovery');
  parts.push('When starting significant work (not small fixes):');
  parts.push('1. Check installed agents in `agents/` — pick the best match for this task');
  parts.push('2. If no matching agent is installed, run `agentctx agents list --all` to check available specialists');
  parts.push('3. If a relevant specialist exists, suggest: "A {name} agent is available for this type of work. Add it with: `agentctx sync --agent {slug}`"');
  parts.push('4. If task spans multiple domains and multiple agents are installed, suggest `/build-with-team` for parallel work');
  parts.push('5. Read the selected agent\'s file before starting work');
  parts.push('');
  parts.push('### System awareness');
  parts.push('- Stale modules? Suggest `agentctx sync`');
  parts.push('- Missing skill? Suggest `agentctx sync --add {skill}`');
  parts.push('- Empty architecture? Offer to fill it from codebase');

  return parts.join('\n') + '\n';
}
