import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';

export function generateCursorrules(
  modules: ContextModule[],
  config: AgentCtxConfig,
): string {
  const parts: string[] = [
    `# Cursor Rules for ${config.project.name}`,
    '# Generated by agentctx — do not edit directly',
    '#',
    '# Context lives in .agentctx/context/ — read files based on what you need:',
    '#   conventions/*.md  — code patterns and anti-patterns',
    '#   modules/*.md      — what code exists (check before creating new)',
    '#   agents/*.md       — agent personality',
    '#   architecture.md   — where to put new files',
    '#   decisions.md      — past architectural decisions',
    '#   references/*.md   — syntax quick references',
    '',
  ];

  if (config.project.language) parts.push(`# Language: ${config.project.language}`);
  if (config.project.framework) parts.push(`# Framework: ${config.project.framework}`);
  if (config.agent) parts.push(`# Agent: ${config.agent}`);
  parts.push('');
  parts.push('# Before writing code: check modules/ for existing exports, read conventions/');
  parts.push('# After implementing: update modules/{feature}.md, log decisions, update status');
  parts.push('# New feature? Suggest /spec first');

  return parts.join('\n') + '\n';
}
