import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';
import { basename, extname } from 'node:path';

function shouldIncludeModule(
  mod: ContextModule,
  sections: { include: string[]; exclude: string[] },
): boolean {
  const stem = basename(mod.filename, extname(mod.filename));
  if (sections.exclude.length > 0 && sections.exclude.includes(stem)) {
    return false;
  }
  if (sections.include.length > 0 && !sections.include.includes(stem)) {
    return false;
  }
  return true;
}

export function generateCursorrules(
  modules: ContextModule[],
  config: AgentCtxConfig,
): string {
  const sections = config.outputs.cursorrules?.sections ?? {
    include: [],
    exclude: [],
  };

  const filtered = modules.filter((m) => shouldIncludeModule(m, sections));

  const parts: string[] = [
    `# Cursor Rules for ${config.project.name}`,
    '# Generated by agentctx — do not edit directly',
  ];

  for (const mod of filtered) {
    parts.push('');
    parts.push(mod.content.trim());
  }

  return parts.join('\n') + '\n';
}
