import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';

// All generators produce thin routing files pointing to .agentctx/context/
// The AI reads the thin file, then reads specific context files on demand.

function metaLine(config: AgentCtxConfig): string {
  const parts: string[] = [];
  if (config.project.language) parts.push(config.project.language);
  if (config.project.framework) parts.push(config.project.framework);
  if (config.agent) parts.push(`Agent: ${config.agent}`);
  return parts.join(' | ');
}

function contextTable(): string {
  return [
    '| Need | Path | When |',
    '|------|------|------|',
    '| Code conventions | `conventions/*.md` | Before writing code |',
    '| What exists | `modules/*.md` | Before creating new code |',
    '| Agent personality | `agents/*.md` | Start of conversation |',
    '| Architecture | `architecture.md` | Where to put files |',
    '| Decisions | `decisions.md` | Choosing approaches |',
    '| References | `references/*.md` | Looking up syntax |',
  ].join('\n');
}

function protocol(): string {
  return [
    'Before writing code: check modules/ for reusable exports, read conventions/',
    'After implementing: update modules/{feature}.md, log decisions, update status',
    'New feature? Suggest /spec first',
  ].join('\n');
}

// ── GitHub Copilot ────────────────────────────────────────────────────

export function generateCopilot(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Copilot Instructions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`. Read files based on what you need:',
    '',
    contextTable(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Aider ─────────────────────────────────────────────────────────────

export function generateAider(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Conventions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context: `.agentctx/context/`',
    '- `conventions/*.md` — code patterns',
    '- `modules/*.md` — what code exists',
    '- `architecture.md` — project structure',
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Windsurf ──────────────────────────────────────────────────────────

export function generateWindsurf(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# Windsurf Rules for ${config.project.name}`,
    '# Generated by agentctx',
    '',
    `# ${metaLine(config)}`,
    '',
    '# Context: .agentctx/context/',
    '#   conventions/*.md — code patterns and anti-patterns',
    '#   modules/*.md — what code exists',
    '#   architecture.md — project structure',
    '',
    '# Before code: check modules/, read conventions/',
    '# After implementing: update modules/{feature}.md',
    '',
  ].join('\n');
}

// ── Codex ─────────────────────────────────────────────────────────────

export function generateCodex(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Agent Instructions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`. Read files based on what you need:',
    '',
    contextTable(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Gemini ────────────────────────────────────────────────────────────

export function generateGemini(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Project Context`,
    '<!-- Generated by agentctx for Gemini CLI -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`. Read files based on what you need:',
    '',
    contextTable(),
    '',
    protocol(),
    '',
  ].join('\n');
}
