import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';
import { basename, extname } from 'node:path';

// ── Shared utilities ──────────────────────────────────────────────────

function shouldIncludeModule(
  mod: ContextModule,
  sections?: { include: string[]; exclude: string[] },
): boolean {
  if (!sections) return true;
  const stem = basename(mod.filename, extname(mod.filename));
  if (sections.exclude.length > 0 && sections.exclude.includes(stem)) return false;
  if (sections.include.length > 0 && !sections.include.includes(stem)) return false;
  return true;
}

function getFiltered(modules: ContextModule[], config: AgentCtxConfig, outputKey: string): ContextModule[] {
  const sections = config.outputs[outputKey]?.sections ?? { include: [], exclude: [] };
  return modules.filter(m => shouldIncludeModule(m, sections));
}

function stripHeading(content: string): string {
  return content.replace(/^#\s+.+\n?/, '').trim();
}

// ── GitHub Copilot (.github/copilot-instructions.md) ──────────────────

export function generateCopilot(modules: ContextModule[], config: AgentCtxConfig): string {
  const filtered = getFiltered(modules, config, 'copilot');

  const parts: string[] = [
    `# Copilot Instructions for ${config.project.name}`,
    '<!-- Generated by agentctx — do not edit directly -->',
    '',
  ];

  if (config.project.language) {
    parts.push(`Language: ${config.project.language}`);
  }
  if (config.project.framework) {
    parts.push(`Framework: ${config.project.framework}`);
  }
  if (config.project.language || config.project.framework) {
    parts.push('');
  }

  for (const mod of filtered) {
    parts.push(`## ${mod.title}`);
    parts.push('');
    parts.push(stripHeading(mod.content));
    parts.push('');
  }

  return parts.join('\n');
}

// ── Aider (CONVENTIONS.md) ────────────────────────────────────────────

export function generateAider(modules: ContextModule[], config: AgentCtxConfig): string {
  const filtered = getFiltered(modules, config, 'aider');

  const parts: string[] = [
    `# Conventions for ${config.project.name}`,
    '<!-- Generated by agentctx -->',
    '',
  ];

  for (const mod of filtered) {
    parts.push(`## ${mod.title}`);
    parts.push('');
    parts.push(stripHeading(mod.content));
    parts.push('');
  }

  return parts.join('\n');
}

// ── Windsurf (.windsurfrules) ─────────────────────────────────────────

export function generateWindsurf(modules: ContextModule[], config: AgentCtxConfig): string {
  const filtered = getFiltered(modules, config, 'windsurf');

  const parts: string[] = [
    `# Windsurf Rules for ${config.project.name}`,
    '# Generated by agentctx',
    '',
  ];

  for (const mod of filtered) {
    parts.push(mod.content.trim());
    parts.push('');
  }

  return parts.join('\n');
}

// ── Codex (AGENTS.md) ─────────────────────────────────────────────────

export function generateCodex(modules: ContextModule[], config: AgentCtxConfig): string {
  const filtered = getFiltered(modules, config, 'codex');

  const parts: string[] = [
    `# ${config.project.name} — Agent Instructions`,
    '<!-- Generated by agentctx -->',
    '',
  ];

  if (config.project.language) {
    parts.push(`- Language: ${config.project.language}`);
  }
  if (config.project.framework) {
    parts.push(`- Framework: ${config.project.framework}`);
  }
  if (config.project.language || config.project.framework) {
    parts.push('');
  }

  for (const mod of filtered) {
    parts.push(`## ${mod.title}`);
    parts.push('');
    parts.push(stripHeading(mod.content));
    parts.push('');
  }

  return parts.join('\n');
}

// ── Gemini (GEMINI.md) ────────────────────────────────────────────────

export function generateGemini(modules: ContextModule[], config: AgentCtxConfig): string {
  const filtered = getFiltered(modules, config, 'gemini');

  const parts: string[] = [
    `# ${config.project.name} — Project Context`,
    '<!-- Generated by agentctx for Gemini CLI -->',
    '',
  ];

  if (config.project.language || config.project.framework) {
    const meta: string[] = [];
    if (config.project.language) meta.push(`**Language:** ${config.project.language}`);
    if (config.project.framework) meta.push(`**Framework:** ${config.project.framework}`);
    parts.push(meta.join(' | '));
    parts.push('');
  }

  for (let i = 0; i < filtered.length; i++) {
    const mod = filtered[i];
    parts.push(`## ${mod.title}`);
    parts.push('');
    parts.push(stripHeading(mod.content));
    if (i < filtered.length - 1) {
      parts.push('');
      parts.push('---');
    }
    parts.push('');
  }

  return parts.join('\n');
}
