import type { ContextModule } from '../core/context.js';
import type { AgentCtxConfig } from '../core/config.js';

// All generators produce thin routing files pointing to .agentctx/context/

function metaLine(config: AgentCtxConfig): string {
  const parts: string[] = [];
  if (config.project.language) parts.push(config.project.language);
  if (config.project.framework) parts.push(config.project.framework);
  if (config.agent) parts.push(`Agent: ${config.agent}`);
  return parts.join(' | ');
}

function contextList(): string {
  return [
    '- `conventions/*.md` — code patterns (read Quick Rules section first)',
    '- `modules/*.md` — what code exists (check before creating new)',
    '- `agents/*.md` — agent personality',
    '- `architecture.md` — where to put new files',
    '- `decisions.md` — past decisions',
    '- `references/*.md` — syntax quick references',
  ].join('\n');
}

function protocol(): string {
  return [
    'Before writing code: check modules/ for reusable exports, read conventions/',
    'After implementing: update modules/{feature}.md, log decisions, update status',
    'New feature? Suggest /spec first',
  ].join('\n');
}

// ── GitHub Copilot (.github/copilot-instructions.md) ──────────────────

export function generateCopilot(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Copilot Instructions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`:',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Aider (CONVENTIONS.md) ────────────────────────────────────────────

export function generateAider(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Conventions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context: `.agentctx/context/`',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Windsurf (.windsurfrules) ─────────────────────────────────────────

export function generateWindsurf(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# Windsurf Rules for ${config.project.name}`,
    '# Generated by agentctx',
    '',
    `# ${metaLine(config)}`,
    '',
    '# Context: .agentctx/context/',
    '#   conventions/*.md — code patterns',
    '#   modules/*.md — what code exists',
    '#   architecture.md — project structure',
    '',
    '# Before code: check modules/, read conventions/',
    '# After implementing: update modules/{feature}.md',
    '',
  ].join('\n');
}

// ── Codex (AGENTS.md) ─────────────────────────────────────────────────

export function generateCodex(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Agent Instructions`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`:',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Gemini CLI (GEMINI.md) ────────────────────────────────────────────

export function generateGemini(_modules: ContextModule[], config: AgentCtxConfig): string {
  return [
    `# ${config.project.name} — Project Context`,
    '<!-- Generated by agentctx for Gemini CLI -->',
    '',
    metaLine(config),
    '',
    'Context lives in `.agentctx/context/`:',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── OpenClaw (SOUL.md + AGENTS.md + IDENTITY.md) ──────────────────────

export function generateOpenclawSoul(_modules: ContextModule[], config: AgentCtxConfig): string {
  // SOUL.md — persona, tone, boundaries
  const parts: string[] = [
    `# ${config.project.name}`,
    '',
  ];

  if (config.agent) {
    parts.push(`Agent personality: read \`.agentctx/context/agents/${config.agent}.md\``);
    parts.push('');
  }

  parts.push('## Communication Style');
  parts.push('- Be direct and specific — reference real file paths');
  parts.push('- Explain trade-offs, not just answers');
  parts.push('- Check existing code before creating new');
  parts.push('');
  parts.push('## Boundaries');
  parts.push('- Follow conventions in `.agentctx/context/conventions/`');
  parts.push('- Log decisions in `decisions.md`');
  parts.push('- Suggest /spec before implementing new features');

  return parts.join('\n') + '\n';
}

export function generateOpenclawAgents(_modules: ContextModule[], config: AgentCtxConfig): string {
  // AGENTS.md — mission, operations, workflow
  return [
    `# ${config.project.name} — Operations`,
    '<!-- Generated by agentctx -->',
    '',
    metaLine(config),
    '',
    'Context: `.agentctx/context/`',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

export function generateOpenclawIdentity(_modules: ContextModule[], config: AgentCtxConfig): string {
  // IDENTITY.md — name + description
  const parts: string[] = [`# ${config.project.name}`];
  if (config.project.language || config.project.framework) {
    parts.push(metaLine(config));
  }
  if (config.agent) {
    parts.push(`Agent: ${config.agent}`);
  }
  return parts.join('\n') + '\n';
}

// ── OpenCode (.opencode/agents/) ──────────────────────────────────────

export function generateOpencode(_modules: ContextModule[], config: AgentCtxConfig): string {
  const name = config.project.name;
  return [
    '---',
    `name: ${name}`,
    `description: "${name} project conventions via agentctx"`,
    'mode: subagent',
    "color: '#58A6FF'",
    '---',
    '',
    `# ${name}`,
    '',
    metaLine(config),
    '',
    'Context: `.agentctx/context/`',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}

// ── Qwen Code (.qwen/agents/) ─────────────────────────────────────────

export function generateQwen(_modules: ContextModule[], config: AgentCtxConfig): string {
  const name = config.project.name;
  const desc = `${name} project conventions and context via agentctx`;
  return [
    '---',
    `name: ${name}`,
    `description: "${desc}"`,
    '---',
    '',
    `# ${name}`,
    '',
    metaLine(config),
    '',
    'Context: `.agentctx/context/`',
    '',
    contextList(),
    '',
    protocol(),
    '',
  ].join('\n');
}
