import { describe, it, expect } from 'vitest';
import { generateClaude } from '../../src/generators/claude.js';
import type { ContextModule } from '../../src/core/context.js';
import type { AgentCtxConfig } from '../../src/core/config.js';

function makeModules(): ContextModule[] {
  return [
    {
      title: 'Principles',
      filename: 'principles.md',
      content: '# Principles\n\nKeep it simple.\nWrite tests first.',
      lastModified: new Date('2025-01-01'),
    },
    {
      title: 'Testing',
      filename: 'testing.md',
      content: '# Testing\n\nUse vitest for all tests.',
      lastModified: new Date('2025-01-02'),
    },
    {
      title: 'Workflows',
      filename: 'workflows.md',
      content: '# Workflows\n\nAlways open a PR.',
      lastModified: new Date('2025-01-03'),
    },
  ];
}

function makeConfig(overrides?: Partial<AgentCtxConfig>): AgentCtxConfig {
  return {
    version: 1 as const,
    project: { name: 'test-project' },
    skills: [],
    context: ['context/principles.md', 'context/testing.md'],
    outputs: {
      claude: {
        enabled: true,
        path: 'CLAUDE.md',
        max_tokens: 8000,
        sections: { include: [], exclude: [] },
      },
      cursorrules: {
        enabled: true,
        path: '.cursorrules',
        max_tokens: 4000,
        sections: { include: [], exclude: [] },
      },
    },
    references: [],
    lint: {
      token_budgets: true,
      broken_refs: true,
      freshness: { enabled: true, stale_days: 30 },
    },
    ...overrides,
  };
}

describe('generateClaude', () => {
  it('produces correct header comments', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain(
      '<!-- Generated by agentctx — do not edit directly -->',
    );
    expect(result).toContain(
      '<!-- Source: .agentctx/ | Regenerate: npx agentctx generate -->',
    );
  });

  it('includes project name as H1', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('# test-project');
  });

  it('renders each module as an H2 section', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('## Principles');
    expect(result).toContain('## Testing');
    expect(result).toContain('## Workflows');
  });

  it('strips the original H1 heading from module content', () => {
    const result = generateClaude(makeModules(), makeConfig());
    // Should not have "# Principles" as a standalone H1 (only ## Principles)
    const h1Matches = result.match(/^# Principles$/m);
    expect(h1Matches).toBeNull();
  });

  it('includes module body content', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('Keep it simple.');
    expect(result).toContain('Use vitest for all tests.');
    expect(result).toContain('Always open a PR.');
  });

  it('separates modules with ---', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('---');
    // Should have separators between modules (2 for 3 modules) + 1 before Context Maintenance Protocol
    const separators = result.match(/^---$/gm);
    expect(separators).toHaveLength(3);
  });

  it('filters out excluded sections', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: [], exclude: ['workflows'] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude(makeModules(), config);
    expect(result).toContain('## Principles');
    expect(result).toContain('## Testing');
    expect(result).not.toContain('## Workflows');
    expect(result).not.toContain('Always open a PR.');
  });

  it('filters to only included sections when include is set', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: ['principles'], exclude: [] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude(makeModules(), config);
    expect(result).toContain('## Principles');
    expect(result).not.toContain('## Testing');
    expect(result).not.toContain('## Workflows');
  });

  it('returns empty body when all modules are excluded (except protocol)', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: {
            include: [],
            exclude: ['principles', 'testing', 'workflows'],
          },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude([], config);
    expect(result).toContain('# test-project');
    // Should only have the Context Maintenance Protocol section, no module sections
    expect(result).not.toContain('## Principles');
    expect(result).not.toContain('## Testing');
    expect(result).not.toContain('## Workflows');
    expect(result).toContain('## Context Maintenance Protocol');
  });
});
