import { describe, it, expect } from 'vitest';
import { generateClaude } from '../../src/generators/claude.js';
import type { ContextModule } from '../../src/core/context.js';
import type { AgentCtxConfig } from '../../src/core/config.js';

function makeModules(): ContextModule[] {
  return [
    {
      title: 'Routing',
      filename: 'routing.md',
      content: '# Routing\n\nUse App Router for all routes.',
      lastModified: new Date('2025-01-01'),
    },
    {
      title: 'Data Fetching',
      filename: 'data-fetching.md',
      content: '# Data Fetching\n\nUse server components for data fetching.',
      lastModified: new Date('2025-01-02'),
    },
    {
      title: 'Auth Module',
      filename: 'auth.md',
      content: '# Auth Module\n\n## Key Files\n- `src/auth/index.ts` — main auth logic\n\n## Exports\n- `signIn()` — sign in user\n- `signOut()` — sign out user',
      lastModified: new Date('2025-01-03'),
    },
  ];
}

function makeConfig(overrides?: Partial<AgentCtxConfig>): AgentCtxConfig {
  return {
    version: 1 as const,
    project: { name: 'test-project', language: 'typescript', framework: 'nextjs' },
    skills: ['nextjs', 'tailwind'],
    context: [
      'context/conventions/nextjs/routing.md',
      'context/conventions/nextjs/data-fetching.md',
      'context/modules/auth.md',
      'context/architecture.md',
      'context/decisions.md',
      'context/status.md',
    ],
    outputs: {
      claude: {
        enabled: true,
        path: 'CLAUDE.md',
        max_tokens: 8000,
        sections: { include: [], exclude: [] },
      },
      cursorrules: {
        enabled: true,
        path: '.cursorrules',
        max_tokens: 4000,
        sections: { include: [], exclude: [] },
      },
    },
    references: [],
    lint: {
      token_budgets: true,
      broken_refs: true,
      freshness: { enabled: true, stale_days: 30 },
    },
    ...overrides,
  };
}

describe('generateClaude', () => {
  it('produces correct header comment', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain(
      '<!-- Generated by agentctx — do not edit directly -->',
    );
  });

  it('includes project name as H1', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('# test-project');
  });

  it('includes metadata line with language, framework, skills', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('typescript');
    expect(result).toContain('nextjs');
    expect(result).toContain('Skills: nextjs, tailwind');
  });

  it('includes agent in metadata when configured', () => {
    const result = generateClaude(makeModules(), makeConfig({ agent: 'frontend-developer' }));
    expect(result).toContain('Agent: frontend-developer');
  });

  it('renders Context Routing table', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('## Context Routing');
    expect(result).toContain('conventions/{skill}/*.md');
    expect(result).toContain('modules/*.md');
    expect(result).toContain('architecture.md');
  });

  it('only shows routing rows for directories that have files', () => {
    const config = makeConfig({
      context: ['context/conventions/nextjs/routing.md'],
    });
    const modules = [makeModules()[0]];
    const result = generateClaude(modules, config);
    expect(result).toContain('conventions/');
    // Task routing always mentions modules for "New feature area" row
    expect(result).not.toContain('agents/*.md');
    expect(result).not.toContain('references/{skill}/*.md');
  });

  it('renders Module Index for feature modules', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('## Module Index');
    expect(result).toContain('**Auth Module**');
    expect(result).toContain('modules/auth.md');
    expect(result).toContain('`signIn()`');
    expect(result).toContain('`src/auth/index.ts`');
  });

  it('does not render Module Index when no feature modules exist', () => {
    const config = makeConfig({
      context: ['context/conventions/routing.md'],
    });
    const modules = [makeModules()[0]];
    const result = generateClaude(modules, config);
    expect(result).not.toContain('## Module Index');
  });

  it('does NOT render convention content inline', () => {
    const result = generateClaude(makeModules(), makeConfig());
    // Convention content should NOT be dumped inline
    expect(result).not.toContain('Use App Router for all routes.');
    expect(result).not.toContain('Use server components for data fetching.');
  });

  it('renders compact Protocol section', () => {
    const result = generateClaude(makeModules(), makeConfig());
    expect(result).toContain('## Protocol');
    expect(result).toContain('### Before writing code');
    expect(result).toContain('### After implementing');
    expect(result).toContain('### System awareness');
    // Should NOT have the old verbose Context Maintenance Protocol
    expect(result).not.toContain('## Context Maintenance Protocol');
  });

  it('filters out excluded sections', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: [], exclude: ['auth'] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude(makeModules(), config);
    expect(result).not.toContain('**Auth Module**');
  });

  it('filters to only included sections when include is set', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: ['routing'], exclude: [] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude(makeModules(), config);
    // Only routing should show in the routing table analysis
    // But auth and data-fetching should be excluded
    expect(result).not.toContain('**Auth Module**');
  });

  it('returns header and protocol when all modules are excluded', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: {
            include: [],
            exclude: ['routing', 'data-fetching', 'auth'],
          },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: [] },
        },
      },
    });
    const result = generateClaude([], config);
    expect(result).toContain('# test-project');
    expect(result).toContain('## Protocol');
    expect(result).not.toContain('## Module Index');
  });

  it('produces output under 2K tokens for typical config', () => {
    const result = generateClaude(makeModules(), makeConfig());
    // Rough token estimate: ~4 chars per token
    const estimatedTokens = Math.ceil(result.length / 4);
    expect(estimatedTokens).toBeLessThan(2000);
  });
});
