import { describe, it, expect } from 'vitest';
import { generateCursorrules } from '../../src/generators/cursorrules.js';
import type { ContextModule } from '../../src/core/context.js';
import type { AgentCtxConfig } from '../../src/core/config.js';

function makeModules(): ContextModule[] {
  return [
    {
      title: 'Principles',
      filename: 'principles.md',
      content: '# Principles\n\nKeep it simple.\nWrite tests first.',
      lastModified: new Date('2025-01-01'),
    },
    {
      title: 'Testing',
      filename: 'testing.md',
      content: '# Testing\n\nUse vitest for all tests.',
      lastModified: new Date('2025-01-02'),
    },
    {
      title: 'Workflows',
      filename: 'workflows.md',
      content: '# Workflows\n\nAlways open a PR.',
      lastModified: new Date('2025-01-03'),
    },
  ];
}

function makeConfig(overrides?: Partial<AgentCtxConfig>): AgentCtxConfig {
  return {
    version: 1 as const,
    project: { name: 'test-project' },
    skills: [],
    context: ['context/principles.md', 'context/testing.md'],
    outputs: {
      claude: {
        enabled: true,
        path: 'CLAUDE.md',
        max_tokens: 8000,
        sections: { include: [], exclude: [] },
      },
      cursorrules: {
        enabled: true,
        path: '.cursorrules',
        max_tokens: 4000,
        sections: { include: [], exclude: [] },
      },
    },
    references: [],
    lint: {
      token_budgets: true,
      broken_refs: true,
      freshness: { enabled: true, stale_days: 30 },
    },
    ...overrides,
  };
}

describe('generateCursorrules', () => {
  it('produces correct header with project name', () => {
    const result = generateCursorrules(makeModules(), makeConfig());
    expect(result).toContain('# Cursor Rules for test-project');
  });

  it('includes generated-by comment', () => {
    const result = generateCursorrules(makeModules(), makeConfig());
    expect(result).toContain(
      '# Generated by agentctx — do not edit directly',
    );
  });

  it('includes all module content', () => {
    const result = generateCursorrules(makeModules(), makeConfig());
    expect(result).toContain('Keep it simple.');
    expect(result).toContain('Use vitest for all tests.');
    expect(result).toContain('Always open a PR.');
  });

  it('preserves module headings in content', () => {
    const result = generateCursorrules(makeModules(), makeConfig());
    // Cursorrules does NOT strip headings (unlike claude generator)
    expect(result).toContain('# Principles');
    expect(result).toContain('# Testing');
    expect(result).toContain('# Workflows');
  });

  it('filters out excluded sections', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: [], exclude: [] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: [], exclude: ['workflows'] },
        },
      },
    });
    const result = generateCursorrules(makeModules(), config);
    expect(result).toContain('# Principles');
    expect(result).toContain('# Testing');
    expect(result).not.toContain('# Workflows');
    expect(result).not.toContain('Always open a PR.');
  });

  it('filters to only included sections when include is set', () => {
    const config = makeConfig({
      outputs: {
        claude: {
          enabled: true,
          path: 'CLAUDE.md',
          sections: { include: [], exclude: [] },
        },
        cursorrules: {
          enabled: true,
          path: '.cursorrules',
          sections: { include: ['testing'], exclude: [] },
        },
      },
    });
    const result = generateCursorrules(makeModules(), config);
    expect(result).not.toContain('# Principles');
    expect(result).toContain('# Testing');
    expect(result).not.toContain('# Workflows');
  });

  it('handles empty modules list', () => {
    const result = generateCursorrules([], makeConfig());
    expect(result).toContain('# Cursor Rules for test-project');
    expect(result).toContain('# Generated by agentctx');
  });
});
